import { z } from "zod";

const EnvSchema = z.object({
  DATABASE_URL: z.string().min(1),
  JWT_SECRET: z.string().min(16),
  INTERNAL_ADMIN_SECRET: z.string().min(16).optional(),
  R2_BUCKET: z.string().min(1).optional(),
  R2_ACCOUNT_ID: z.string().min(1).optional(),
  R2_ACCESS_KEY_ID: z.string().min(1).optional(),
  R2_SECRET_ACCESS_KEY: z.string().min(1).optional(),
  R2_PUBLIC_BASE_URL: z.string().url().optional(),
  ACCESS_TOKEN_TTL_SECONDS: z.coerce.number().int().positive().default(3600),
  REFRESH_TOKEN_TTL_SECONDS: z.coerce.number().int().positive().default(60 * 60 * 24 * 30),
  PASSWORD_RESET_TOKEN_TTL_SECONDS: z.coerce.number().int().positive().default(60 * 30),
  RETURN_RESET_TOKEN: z.coerce.boolean().default(true),
  SMTP_HOST: z.string().optional(),
  SMTP_PORT: z.coerce.number().int().positive().optional(),
  SMTP_SECURE: z.coerce.boolean().optional(),
  SMTP_USER: z.string().optional(),
  SMTP_PASS: z.string().optional(),
  SMTP_FROM: z.string().optional(),
  SMTP_DEBUG: z.coerce.boolean().optional(),
  POWERSYNC_JWT_AUDIENCE: z.string().min(1).default("powersync"),
  POWERSYNC_JWT_KID: z.string().min(1).default("kasirgo-hs256"),
  HOSTNAME: z.string().min(1).default("0.0.0.0"),
  PORT: z.coerce.number().int().positive().default(8787),
});

export const env = EnvSchema.parse({
  DATABASE_URL: Bun.env.DATABASE_URL,
  JWT_SECRET: Bun.env.JWT_SECRET,
    INTERNAL_ADMIN_SECRET: Bun.env.INTERNAL_ADMIN_SECRET,
  R2_BUCKET: Bun.env.R2_BUCKET,
  R2_ACCOUNT_ID: Bun.env.R2_ACCOUNT_ID,
  R2_ACCESS_KEY_ID: Bun.env.R2_ACCESS_KEY_ID,
  R2_SECRET_ACCESS_KEY: Bun.env.R2_SECRET_ACCESS_KEY,
  R2_PUBLIC_BASE_URL: Bun.env.R2_PUBLIC_BASE_URL,
  ACCESS_TOKEN_TTL_SECONDS: Bun.env.ACCESS_TOKEN_TTL_SECONDS,
  REFRESH_TOKEN_TTL_SECONDS: Bun.env.REFRESH_TOKEN_TTL_SECONDS,
  PASSWORD_RESET_TOKEN_TTL_SECONDS: Bun.env.PASSWORD_RESET_TOKEN_TTL_SECONDS,
  RETURN_RESET_TOKEN: Bun.env.RETURN_RESET_TOKEN,
  SMTP_HOST: Bun.env.SMTP_HOST,
  SMTP_PORT: Bun.env.SMTP_PORT,
  SMTP_SECURE: Bun.env.SMTP_SECURE,
  SMTP_USER: Bun.env.SMTP_USER,
  SMTP_PASS: Bun.env.SMTP_PASS,
  SMTP_FROM: Bun.env.SMTP_FROM,
  SMTP_DEBUG: Bun.env.SMTP_DEBUG,
  POWERSYNC_JWT_AUDIENCE: Bun.env.POWERSYNC_JWT_AUDIENCE,
  POWERSYNC_JWT_KID: Bun.env.POWERSYNC_JWT_KID,
  HOSTNAME: Bun.env.HOSTNAME,
  PORT: Bun.env.PORT,
});
